"""add content_fingerprint

Revision ID: 0b692c2d7c13
Revises: efff538b1124
Create Date: 2026-04-08 20:33:31.370637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b692c2d7c13'
down_revision: Union[str, Sequence[str], None] = 'efff538b1124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('content_fingerprint', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'memories', ['content_fingerprint'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memories', type_='unique')
    op.drop_column('memories', 'content_fingerprint')
    # ### end Alembic commands ###
