"""add owner and agent_tokens tables

Revision ID: 4bfa7b5e03e9
Revises: 0b692c2d7c13
Create Date: 2026-04-11 18:15:28.694596

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4bfa7b5e03e9"
down_revision: Union[str, Sequence[str], None] = "0b692c2d7c13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_tokens_agent_id"), "agent_tokens", ["agent_id"], unique=False
    )
    op.create_index(
        "ix_agent_tokens_agent_id_active",
        "agent_tokens",
        ["agent_id", "revoked_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_tokens_revoked_at"), "agent_tokens", ["revoked_at"], unique=False
    )
    op.create_index(
        op.f("ix_agent_tokens_token_hash"), "agent_tokens", ["token_hash"], unique=True
    )
    op.create_table(
        "owner",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_setup", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_owner_email"), "owner", ["email"], unique=False)
    op.create_index(op.f("ix_owner_is_setup"), "owner", ["is_setup"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_owner_is_setup"), table_name="owner")
    op.drop_index(op.f("ix_owner_email"), table_name="owner")
    op.drop_table("owner")
    op.drop_index(op.f("ix_agent_tokens_token_hash"), table_name="agent_tokens")
    op.drop_index(op.f("ix_agent_tokens_revoked_at"), table_name="agent_tokens")
    op.drop_index("ix_agent_tokens_agent_id_active", table_name="agent_tokens")
    op.drop_index(op.f("ix_agent_tokens_agent_id"), table_name="agent_tokens")
    op.drop_table("agent_tokens")
    # ### end Alembic commands ###
