"""initial

Revision ID: efff538b1124
Revises:
Create Date: 2026-04-08 20:13:06.801968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "efff538b1124"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence_with_content",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("generation_id", sa.UUID(), nullable=False),
        sa.Column("memory_id", sa.UUID(), nullable=True),
        sa.Column("memory_content", sa.Text(), nullable=True),
        sa.Column("memory_source", sa.String(), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("chunk_content", sa.Text(), nullable=True),
        sa.Column("neo4j_node_id", sa.String(), nullable=True),
        sa.Column("neo4j_rel_type", sa.String(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("retrieval_type", sa.String(), nullable=False),
        sa.Column("relevance_score", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "memories",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('telegram', 'claude', 'agent', 'manual', 'import', 'system')",
            name="memories_source_check",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_memories_captured_at", "memories", ["captured_at"], unique=False
    )
    op.create_index(
        "idx_memories_metadata",
        "memories",
        ["metadata"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("idx_memories_session_id", "memories", ["session_id"], unique=False)
    op.create_index("idx_memories_source", "memories", ["source"], unique=False)
    op.create_table(
        "skills",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("prompt_template", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_skills_active_where_active",
        "skills",
        ["active"],
        unique=False,
        postgresql_where=sa.text("active = true"),
    )
    op.create_index(op.f("ix_skills_name"), "skills", ["name"], unique=True)
    op.create_table(
        "chunks",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("memory_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("qdrant_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["memory_id"], ["memories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("qdrant_id"),
    )
    op.create_index("idx_chunks_memory_id", "chunks", ["memory_id"], unique=False)
    op.create_index("idx_chunks_qdrant_id", "chunks", ["qdrant_id"], unique=False)
    op.create_table(
        "entities",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("memory_id", sa.UUID(), nullable=False),
        sa.Column("neo4j_node_id", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "label IN ('Project', 'Concept', 'Person', 'Session', 'Event', 'Decision', 'Tool', 'Location')",
            name="entities_label_check",
        ),
        sa.ForeignKeyConstraint(["memory_id"], ["memories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_entities_label", "entities", ["label"], unique=False)
    op.create_index("idx_entities_memory_id", "entities", ["memory_id"], unique=False)
    op.create_index(
        "idx_entities_neo4j_node_id", "entities", ["neo4j_node_id"], unique=False
    )
    op.create_index(
        "idx_entities_neo4j_unique", "entities", ["neo4j_node_id"], unique=True
    )
    op.create_table(
        "generations",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("skill_id", sa.UUID(), nullable=True),
        sa.Column("skill_name", sa.String(), nullable=True),
        sa.Column("output", sa.Text(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("machine", sa.String(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("prompt_used", sa.Text(), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_generations_generated_at", "generations", ["generated_at"], unique=False
    )
    op.create_index("idx_generations_machine", "generations", ["machine"], unique=False)
    op.create_index(
        "idx_generations_session_id", "generations", ["session_id"], unique=False
    )
    op.create_index(
        "idx_generations_skill_id", "generations", ["skill_id"], unique=False
    )
    op.create_index(
        "idx_generations_skill_name", "generations", ["skill_name"], unique=False
    )
    op.create_index(
        op.f("ix_generations_skill_name"), "generations", ["skill_name"], unique=False
    )
    op.create_table(
        "evidence",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("generation_id", sa.UUID(), nullable=False),
        sa.Column("memory_id", sa.UUID(), nullable=True),
        sa.Column("chunk_id", sa.UUID(), nullable=True),
        sa.Column("neo4j_node_id", sa.String(), nullable=True),
        sa.Column("neo4j_rel_type", sa.String(), nullable=True),
        sa.Column("relevance_score", sa.Float(), nullable=True),
        sa.Column("retrieval_type", sa.String(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chunk_id"], ["chunks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["generation_id"], ["generations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["memory_id"], ["memories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_evidence_chunk_id", "evidence", ["chunk_id"], unique=False)
    op.create_index(
        "idx_evidence_generation_id", "evidence", ["generation_id"], unique=False
    )
    op.create_index("idx_evidence_memory_id", "evidence", ["memory_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_evidence_memory_id", table_name="evidence")
    op.drop_index("idx_evidence_generation_id", table_name="evidence")
    op.drop_index("idx_evidence_chunk_id", table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_generations_skill_name"), table_name="generations")
    op.drop_index("idx_generations_skill_name", table_name="generations")
    op.drop_index("idx_generations_skill_id", table_name="generations")
    op.drop_index("idx_generations_session_id", table_name="generations")
    op.drop_index("idx_generations_machine", table_name="generations")
    op.drop_index("idx_generations_generated_at", table_name="generations")
    op.drop_table("generations")
    op.drop_index("idx_entities_neo4j_unique", table_name="entities")
    op.drop_index("idx_entities_neo4j_node_id", table_name="entities")
    op.drop_index("idx_entities_memory_id", table_name="entities")
    op.drop_index("idx_entities_label", table_name="entities")
    op.drop_table("entities")
    op.drop_index("idx_chunks_qdrant_id", table_name="chunks")
    op.drop_index("idx_chunks_memory_id", table_name="chunks")
    op.drop_table("chunks")
    op.drop_index(op.f("ix_skills_name"), table_name="skills")
    op.drop_index(
        "idx_skills_active_where_active",
        table_name="skills",
        postgresql_where=sa.text("active = true"),
    )
    op.drop_table("skills")
    op.drop_index("idx_memories_source", table_name="memories")
    op.drop_index("idx_memories_session_id", table_name="memories")
    op.drop_index(
        "idx_memories_metadata", table_name="memories", postgresql_using="gin"
    )
    op.drop_index("idx_memories_captured_at", table_name="memories")
    op.drop_table("memories")
    op.drop_table("evidence_with_content")
    # ### end Alembic commands ###
