# neo4j.conf — Core Neo4j settings only
# strict_validation must be disabled BEFORE APOC loads, so it goes here
server.config.strict_validation.enabled=false
dbms.security.auth_enabled=true
server.default_listen_address=0.0.0.0

server.memory.pagecache.size=512M
server.directories.logs=/logs
dbms.security.procedures.unrestricted=apoc.*
USERNAME=neo4j
URI=bolt://localhost:7687
PASSWORD=519620f6f1949c4eac55159b636b323c
