"""Relationship types for the Neo4j graph."""

from enum import Enum


class RelationshipType(str, Enum):
    """
    Canonical relationship types.

    Agents may write custom relationship types beyond this enum — Cypher
    accepts any string as a relationship type. This enum defines the
    standard set for consistency and IDE support.
    """

    # Memory / Event / Fact
    DESCRIBES = "DESCRIBES"  # MemoryChunk describes Event (and vice versa)
    DERIVED_FROM = "DERIVED_FROM"  # Fact is derived from MemoryChunk or Event
    REPLACES = "REPLACES"  # Newer Fact supersedes older Fact
    OVERRIDES = "OVERRIDES"  # Newer Fact overrides older Fact

    # Temporal
    OCCURRED_ON = "OCCURRED_ON"  # Event occurred on a Date
    APPLIES_DURING = "APPLIES_DURING"  # Fact applies during a Period
    HAPPENED_BEFORE = "HAPPENED_BEFORE"  # Event A happened before Event B
    HAPPENED_AFTER = "HAPPENED_AFTER"  # Event A happened after Event B

    # Policy / Contract
    APPLIES_TO = "APPLIES_TO"  # Policy applies to Tenant or Agent
    REQUIRES = "REQUIRES"  # Policy requires Fact; EvidencePath requires Policy
    GOVERNS = "GOVERNS"  # Contract governs Agent or Tenant
    AUTHORIZED_BY = "AUTHORIZED_BY"  # Agent authorized by Contract

    # Evidence layer
    USED = "USED"  # EvidencePath used MemoryChunk/Event/Fact
    FOLLOWED = "FOLLOWED"  # EvidencePath followed an Edge type
    PRODUCED = "PRODUCED"  # EvidencePath produced Output
    GENERATED_BY = "GENERATED_BY"  # EvidencePath generated by Agent
    BELONGS_TO = "BELONGS_TO"  # EvidencePath belongs to Tenant;
    # EvidenceStep belongs to EvidencePath
    NEXT = "NEXT"  # EvidenceStep → next EvidenceStep

    # Structural
    IN_SESSION = "IN_SESSION"  # MemoryChunk belongs to a session
